name: obfuscate
description: Dart CLI tool and library for text obfuscation and deobfuscation using custom mapping, Base64, ROT13, XOR, and string reversal.
version: 0.0.1
homepage: https://github.com/bardiakz/obfuscate
repository: https://github.com/bardiakz/obfuscate

# CLI executable
executables:
  obfuscate:

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  args: ^2.7.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

topics:
  - cli
  - obfuscation
  - encryption
  - text-processing
  - security