name: obfuscate
description: Dart CLI tool and library for text obfuscation and deobfuscation using custom mapping, Base64, ROT13, XOR, and string reversal.
version: 0.0.1
homepage: https://github.com/bardiakz/obfuscate
repository: https://github.com/bardiakz/obfuscate

environment:
  sdk: '>=2.17.0 <4.0.0'

# CLI executable
executables:
  obfuscate:

dependencies:
  args: ^2.4.0

dev_dependencies:
  test: ^1.21.0
  lints: ^2.0.0

topics:
  - cli
  - obfuscation
  - encryption
  - text-processing
  - security